# Generated by Django 3.0.4 on 2020-04-20 15:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='vw.jpg', max_length=500, upload_to=accounts.models.upload_profile_pic),
        ),
    ]
