# Generated by Django 3.0.4 on 2020-04-21 13:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200421_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='vw.jpg', max_length=500, null=True, upload_to=accounts.models.upload_profile_pic),
        ),
    ]
