# Generated by Django 3.0.4 on 2020-04-21 13:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200421_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpicture',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=blog.models.upload_location_blog_pics),
        ),
    ]
